#!/usr/bin/env bash
#This script  that loops from 1 to 10 with 3 conditions

n="0"
while [ $i -lt 10 ]
do
	if ((n == 3))
	then
		echo "bad luck"
	elif ((n == 7))
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
